list: $/gemfourmedia/gcompany/models/feedback/columns.yaml
modelClass: GemFourMedia\GCompany\Models\Feedback
title: Feedback
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcompany/feedback/update/:id'
