list: $/gemfourmedia/gcompany/models/client/columns.yaml
modelClass: GemFourMedia\GCompany\Models\Client
title: Client
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcompany/client/update/:id'
