list: $/gemfourmedia/gcompany/models/category/columns.yaml
modelClass: GemFourMedia\GCompany\Models\Category
title: Portfolio Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
showTree: true
treeExpanded: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcompany/category/update/portfolio/:id'
