list: $/gemfourmedia/gcompany/models/address/columns.yaml
modelClass: GemFourMedia\GCompany\Models\Address
title: Address
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcompany/address/update/:id'
