list: $/gemfourmedia/gcompany/models/member/columns.yaml
modelClass: GemFourMedia\GCompany\Models\Member
title: Member
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcompany/member/update/:id'
