list: $/gemfourmedia/gcompany/models/article/columns.yaml
modelClass: GemFourMedia\GCompany\Models\Article
title: Service
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcompany/article/update/service/:id'
