list: $/gemfourmedia/gcompany/models/testimonial/columns.yaml
modelClass: GemFourMedia\GCompany\Models\Testimonial
title: Testimonial
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcompany/testimonial/update/:id'
