list: $/gemfourmedia/gcompany/models/info/columns.yaml
modelClass: GemFourMedia\GCompany\Models\Info
title: Info
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcompany/info/update/:id'
