list: $/gemfourmedia/gcompany/models/file/columns.yaml
modelClass: GemFourMedia\GCompany\Models\File
title: File
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcompany/file/update/:id'
